baseURL = "https://blog.fantasticmao.cn"
title = "FantasticMao 个人博客"
theme = "momo"

languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
publishDir = "docs"

enableEmoji = true
googleAnalytics = "G-FBHKYP5SYE"

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            [markup.goldmark.extensions.passthrough]
                enable = true
                [markup.goldmark.extensions.passthrough.delimiters]
                    block = [['$$', '$$']]
                    inline = [['$', '$']]
        [markup.goldmark.renderer]
            unsafe = true
    [markup.highlight]
        style = "github"

[params]
    author = "fantasticmao"
    description = "FantasticMao 个人博客"
    icpRecord = "浙ICP备17009730号"

    customCSS = ["css/custom.css"]

[params.utterances]
    repo = "fantasticmao/blog"
    issueTerm = "og:title"
    theme = "github-light"

[menus]
[[menus.main]]
    name = "首页"
    weight = 1
    url = "/"
[[menus.main]]
    name = "编程技术"
    weight = 2
    url = "/tech"
[[menus.main]]
    name = "生活随笔"
    weight = 3
    url = "/life"
[[menus.main]]
    name = "关于我"
    weight = 4
    url = "/about"
